version: 2

jobs:
  build_and_test:
    docker:
      - image: circleci/python:latest

    steps:
      - checkout

      - run: ./demo.py

      # TODO FIXME switch to tox?
      # - run: pip3 install --user mypy pylint
      # - run: python3 -m mypy --namespace-packages my
      # - run: python3 -m pylint -E my

      # TODO need to keep full mycfg.py as example? to dummy run CI



workflows:
  version: 2
  build_and_test:
    jobs:
      - build_and_test
