version: 2

jobs:
  build_and_test:
    docker:
      - image: circleci/python:latest

    steps:
      - checkout

      - run: ./demo.py
      # TODO need to keep full mycfg.py as example? to dummy run CI

      - run: python3 -m pip install --user tox
      - run: python3 -m tox



workflows:
  version: 2
  build_and_test:
    jobs:
      - build_and_test
